# Generated by Django 4.1 on 2022-09-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                default="1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.unit",
            ),
        ),
    ]
