# Generated by Django 4.1 on 2022-09-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productmodel_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymodel",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="categorymodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="categorymodel",
            name="updated_on",
        ),
    ]
