# Generated by Django 4.1 on 2022-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_categorymodel_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default="1"),
        ),
    ]
