# Generated by Django 4.1 on 2022-09-19 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
